services:

  server:
    container_name: server
    build:
      context: ./services
      dockerfile: ./dockerfiles/server-Dockerfile
    links:
      - mongo
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
    ports:
    - "8000:8000"

  mongo:
        image: mongo
        container_name: mongodb
        volumes:
          - mongodb-data:/data/db
        ports:
          - "27017:27017"

  web:
    container_name: web
    build:
      context: ./services
      dockerfile: ./dockerfiles/web-Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

volumes:
  mongodb-data:
